### ISSUE TITLE
Table 'thinkmall.mall_crm_customer' doesn't exist

### ISSUE THREAD

**Issue by wilhelm000** [thinkcmf/mall#1]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'thinkmall.mall_crm_customer' doesn't exist

这个表应该是在SQL中没有写进去

**Comment by wilhelm000** [comment]
这个是点击订单详情的时候显示的错误

**Comment by yangguangwuwu** [comment]
嗯嗯
